/* =========================================================================
   ESCAPE THE HORDE — co-op networking
   Safe overlay: solo remains untouched; co-op elects one host and mirrors the
   host horde while preserving the existing game.js combat loop.
   ========================================================================= */
'use strict';
window.NET = (function () {
const H = window.HORDE, T = window.THREE;
if (!H || !T) { console.warn('[net] game not loaded'); return {}; }
const CFG = window.HORDE_CONFIG || {};
const URL = CFG.supabaseUrl || 'https://YOUR-PROJECT.supabase.co';
const KEY = CFG.supabaseAnonKey || 'YOUR-ANON-KEY';
const configured = !URL.includes('YOUR-PROJECT') && !KEY.includes('YOUR-ANON-KEY');
const POS_HZ=15, Z_HZ=10, WORLD_HZ=5, INTERP_MS=110, DROP_MS=6500;
const state={on:false,room:null,id:null,name:null,client:null,channel:null,peers:new Map(),isHost:false,started:false,onRoster:null,posT:0,zT:0,worldT:0,seq:0,lastZ:new Map(),remoteZ:new Map(),world:null,wasPlay:false};

const bodyGeo=new T.BoxGeometry(1,1,1), COLS=[0x4ea8de,0xe8b04b,0x6fd66f,0xd96f9a,0xb07fe0,0x59d6c8];
function tag(name,col){const c=document.createElement('canvas');c.width=256;c.height=64;const x=c.getContext('2d');x.font='bold 34px system-ui,sans-serif';x.textAlign='center';x.textBaseline='middle';x.lineWidth=6;x.strokeStyle='rgba(0,0,0,.85)';x.strokeText(name,128,34);x.fillStyle='#'+col.toString(16).padStart(6,'0');x.fillText(name,128,34);const s=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c),transparent:true,depthTest:false,toneMapped:false}));s.scale.set(2,.5,1);s.position.y=2.35;s.renderOrder=50;return s;}
function avatar(name,idx){const col=COLS[idx%COLS.length],g=new T.Group(),kit=new T.MeshLambertMaterial({color:col}),dark=new T.MeshLambertMaterial({color:0x2b2f38}),skin=new T.MeshLambertMaterial({color:0xb98a63});const put=(m,x,y,z,sx,sy,sz)=>{const q=new T.Mesh(bodyGeo,m);q.position.set(x,y,z);q.scale.set(sx,sy,sz);g.add(q);return q;};const torso=put(kit,0,1.15,0,.52,.72,.3),head=put(skin,0,1.68,0,.28,.3,.28);put(dark,0,1.8,0,.31,.1,.31);const armL=put(kit,-.36,1.22,0,.16,.62,.16),armR=put(kit,.36,1.22,0,.16,.62,.16),legL=put(dark,-.15,.42,0,.19,.84,.19),legR=put(dark,.15,.42,0,.19,.84,.19);g.add(tag(name,col));H.scene.add(g);return{g,torso,head,armL,armR,legL,legR};}
function addPeer(id,name,host){if(!id||id===state.id||state.peers.has(id))return;state.peers.set(id,{id,name:name||'SURVIVOR',host:!!host,av:avatar(name||'SURVIVOR',state.peers.size+1),prev:null,next:null,lastSeen:performance.now(),walk:0});H.toast((name||'SURVIVOR')+' JOINED');pushRoster();}
function dropPeer(id){const p=state.peers.get(id);if(!p)return;H.scene.remove(p.av.g);state.peers.delete(id);H.toast((p.name||'SURVIVOR')+' LEFT');electHost();pushRoster();}
function localPos(){const p=H.player;return{i:state.id,n:++state.seq,t:Date.now(),nm:state.name,x:+p.pos.x.toFixed(2),y:+(p.pos.y-H.EYE).toFixed(2),z:+p.pos.z.toFixed(2),r:+p.yaw.toFixed(3),p:+p.pitch.toFixed(3),s:+Math.hypot(p.vel.x,p.vel.z).toFixed(2),c:p.crouch>.5?1:0,h:Math.round(p.hp),w:H.gunState.cur};}
function onPos(m){if(!m||m.i===state.id)return;let p=state.peers.get(m.i);if(!p){addPeer(m.i,m.nm,false);p=state.peers.get(m.i);}if(!p)return;if(p.next&&m.n<=p.next.n)return;p.prev=p.next||m;p.next=m;p.lastSeen=performance.now();}

function zSnap(){const a=[];(H.zombies||[]).forEach((z,i)=>{if(!z||!z.alive)return;a.push({i,a:1,t:z.type,x:+z.g.position.x.toFixed(2),y:+((z.feet!=null?z.feet:z.g.position.y)).toFixed(2),z:+z.g.position.z.toFixed(2),r:+(z.yaw||z.g.rotation.y||0).toFixed(3),hp:Math.round(z.hp),mx:Math.round(z.maxHp||z.hp),s:z.state||'walk',d:z.dying?1:0});});return a;}
function zDelta(cur){const now=new Map(cur.map(z=>[z.i,z])),out=[];now.forEach((z,i)=>{const p=state.lastZ.get(i);if(!p||JSON.stringify(p)!==JSON.stringify(z))out.push(z);});state.lastZ.forEach((z,i)=>{if(!now.has(i))out.push({i,a:0});});state.lastZ=now;return out;}
function spawnRemote(s){let z=state.remoteZ.get(s.i);if(z&&z.alive)return z;const before=new Set((H.zombies||[]).filter(q=>q&&q.alive));if(H.spawn)H.spawn(s.t||'green',Math.max(1,H.game.wave||1),s.y||0);z=(H.zombies||[]).find(q=>q&&q.alive&&!before.has(q));if(!z)z=(H.zombies||[]).find(q=>q&&!q.alive);if(z)state.remoteZ.set(s.i,z);return z;}
function applyZombie(s){if(!s.a){const z=state.remoteZ.get(s.i);if(z){z.alive=false;z.dying=false;if(z.g)z.g.visible=false;if(z.mound)z.mound.visible=false;if(z.moundHit)z.moundHit.visible=false;}state.remoteZ.delete(s.i);return;}const z=spawnRemote(s);if(!z)return;z.alive=true;z.dying=!!s.d;z.type=s.t||z.type;z.hp=s.hp;z.maxHp=s.mx||Math.max(1,s.hp);z.state=s.s||z.state;z.yaw=s.r||0;z.feet=s.y||0;if(z.pos)z.pos.set(s.x,s.y,s.z);if(z.g){z.g.visible=true;z.g.position.set(s.x,s.y,s.z);z.g.rotation.y=s.r||0;}if(z.mound)z.mound.visible=false;if(z.moundHit)z.moundHit.visible=false;}
function onZ(m,key){if(!m||!Array.isArray(m.z)||state.isHost)return;if(key){const live=new Set(m.z.filter(s=>s.a).map(s=>s.i));state.remoteZ.forEach((z,i)=>{if(!live.has(i)){z.alive=false;z.dying=false;if(z.g)z.g.visible=false;state.remoteZ.delete(i);}});}m.z.forEach(applyZombie);}
function suppressGuestLocal(){if(state.isHost||!state.started)return;const keep=new Set(state.remoteZ.values());(H.zombies||[]).forEach(z=>{if(z&&z.alive&&!keep.has(z)){z.alive=false;z.dying=false;if(z.g)z.g.visible=false;}});H.game.toSpawn=0;H.game.zAlive=keep.size;}

function world(){const g=H.game;return{wave:g.wave,inBreak:g.inBreak,breakT:g.breakT,boss:g.boss,phase:g.phase,phaseT:g.phaseT,light:g.light,elapsed:g.elapsed,score:g.score,kills:g.kills,weather:g.weather,weatherT:g.weatherT};}
function onWorld(w){if(!state.isHost)state.world=w;}
function applyWorld(){if(state.isHost||!state.world)return;const g=H.game,w=state.world;['wave','breakT','phaseT','light','elapsed','score','kills','weatherT'].forEach(k=>{if(w[k]!==undefined)g[k]=w[k];});['inBreak','boss','phase','weather'].forEach(k=>{if(w[k]!==undefined)g[k]=w[k];});g.toSpawn=0;}
function nearestZombie(p){let best=null,bd=3.2;for(const z of H.zombies||[]){if(!z||!z.alive||z.dying||!z.g)continue;const d=z.g.position.distanceTo(p);if(d<bd){bd=d;best=z;}}return best;}
function onShot(m){if(!m||m.i===state.id)return;const a=new T.Vector3(m.ax,m.ay,m.az),b=new T.Vector3(m.bx,m.by,m.bz);if(H.tracer)H.tracer(a,b);if(H.Sfx&&H.Sfx.shot){const w=H.WEAPONS[m.w]||H.WEAPONS[0];H.Sfx.shot(w.tone);}if(!state.isHost||!state.started)return;const z=nearestZombie(b);if(!z)return;const w=H.WEAPONS[m.w]||H.WEAPONS[0],base=H.statDmg?H.statDmg(m.w):w.dmg,scale=(H.ZTYPES[z.type]&&H.ZTYPES[z.type].scale)||1,head=b.y>((z.feet||z.g.position.y)+1.35*scale),dmg=base*(head?w.head:1);if(dmg>0&&H.hurtZombie)H.hurtZombie(z,dmg,head,b);}
function onLocalShot(a,b,w){if(!state.on||!state.channel)return;state.channel.send({type:'broadcast',event:'shot',payload:{i:state.id,w,ax:+a.x.toFixed(2),ay:+a.y.toFixed(2),az:+a.z.toFixed(2),bx:+b.x.toFixed(2),by:+b.y.toFixed(2),bz:+b.z.toFixed(2)}});}

function onStart(m){if(!m||m.i===state.id)return;state.started=true;state.wasPlay=true;H.toast('HOST STARTED THE RUN');if(H.game.state!=='play'&&H.restart)H.restart();}
function sendStart(){if(!state.on||!state.isHost||!state.channel)return;state.started=true;state.lastZ.clear();state.channel.send({type:'broadcast',event:'start',payload:{i:state.id,t:Date.now()}});}
async function electHost(){if(!state.on||!state.channel)return;const ps=state.channel.presenceState()||{},ids=Object.keys(ps);if(!ids.includes(state.id))ids.push(state.id);ids.sort();const host=ids[0],was=state.isHost;state.isHost=host===state.id;state.peers.forEach(p=>p.host=p.id===host);if(was!==state.isHost){try{await state.channel.track({name:state.name,host:state.isHost,at:Date.now()});}catch(e){}if(state.isHost)H.toast('YOU ARE THE CO-OP HOST');}pushRoster();}

let loading=null;function loadSB(){if(window.supabase)return Promise.resolve(true);if(loading)return loading;loading=new Promise(resolve=>{let done=false;const f=ok=>{if(!done){done=true;resolve(ok&&!!window.supabase);}};const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=()=>f(true);s.onerror=()=>f(false);document.head.appendChild(s);setTimeout(()=>f(false),8000);});return loading;}
async function join(room,name){if(state.on)return;if(!configured){H.toast('SET YOUR KEYS IN config.js');return;}H.toast('CONNECTING…');if(!(await loadSB())){loading=null;H.toast('CANNOT REACH SUPABASE');return;}state.name=(name||'SURVIVOR').toUpperCase().slice(0,12);state.room=(room||'STREET').toUpperCase().slice(0,12);state.id=Math.random().toString(36).slice(2,10);state.client=window.supabase.createClient(URL,KEY,{realtime:{params:{eventsPerSecond:40}}});state.channel=state.client.channel('horde:'+state.room,{config:{presence:{key:state.id},broadcast:{self:false}}});state.channel.on('broadcast',{event:'pos'},({payload})=>onPos(payload)).on('broadcast',{event:'shot'},({payload})=>onShot(payload)).on('broadcast',{event:'start'},({payload})=>onStart(payload)).on('broadcast',{event:'z'},({payload})=>onZ(payload,false)).on('broadcast',{event:'zk'},({payload})=>onZ(payload,true)).on('broadcast',{event:'world'},({payload})=>onWorld(payload)).on('presence',{event:'join'},({key,newPresences})=>{if(key===state.id)return;const p=newPresences&&newPresences[0];addPeer(key,p&&p.name,p&&p.host);setTimeout(electHost,30);}).on('presence',{event:'sync'},()=>{const ps=state.channel.presenceState()||{};Object.keys(ps).forEach(id=>{if(id===state.id)return;const p=ps[id]&&ps[id][0];addPeer(id,p&&p.name,p&&p.host);});electHost();}).on('presence',{event:'leave'},({key})=>dropPeer(key)).subscribe(async st=>{if(st!=='SUBSCRIBED')return;state.on=true;await state.channel.track({name:state.name,host:false,at:Date.now()});H.toast('JOINED ROOM '+state.room);setTimeout(electHost,60);pushRoster();});}
function host(name){return join(makeRoomCode(),name);}function leave(){if(!state.on)return;state.peers.forEach((p,id)=>{H.scene.remove(p.av.g);});state.peers.clear();state.remoteZ.clear();if(state.channel)state.channel.unsubscribe();state.on=false;state.isHost=false;state.started=false;state.world=null;pushRoster();}

function update(dt){if(!state.on||!state.channel)return;const playing=H.game.state==='play';if(state.isHost&&playing&&!state.wasPlay){sendStart();}state.wasPlay=playing;if(!state.isHost&&state.started){applyWorld();suppressGuestLocal();}
state.posT-=dt;if(state.posT<=0){state.posT=1/POS_HZ;state.channel.send({type:'broadcast',event:'pos',payload:localPos()});}
if(state.isHost&&state.started&&playing){state.zT-=dt;if(state.zT<=0){state.zT=1/Z_HZ;const cur=zSnap(),delta=zDelta(cur),key=(state.seq%10===0)||state.lastZ.size===0;state.channel.send({type:'broadcast',event:key?'zk':'z',payload:{t:Date.now(),z:key?cur:delta}});}state.worldT-=dt;if(state.worldT<=0){state.worldT=1/WORLD_HZ;state.channel.send({type:'broadcast',event:'world',payload:world()});}}
const now=Date.now()-INTERP_MS,clock=performance.now();state.peers.forEach((p,id)=>{if(clock-p.lastSeen>DROP_MS){dropPeer(id);return;}if(!p.next)return;const a=p.prev||p.next,b=p.next,span=Math.max(1,b.t-a.t),k=Math.max(0,Math.min(1,(now-a.t)/span));let dr=b.r-a.r;while(dr>Math.PI)dr-=Math.PI*2;while(dr<-Math.PI)dr+=Math.PI*2;const av=p.av;av.g.position.set(a.x+(b.x-a.x)*k,a.y+(b.y-a.y)*k,a.z+(b.z-a.z)*k);av.g.rotation.y=a.r+dr*k;av.g.scale.y=1-(b.c?1:0)*.32;p.walk+=dt*b.s*1.4;const sw=Math.sin(p.walk)*Math.min(1,b.s/6);av.legL.rotation.x=sw*.7;av.legR.rotation.x=-sw*.7;av.armL.rotation.x=-sw*.4;av.armR.rotation.x=sw*.4;av.head.rotation.x=-(b.p||0)*.6;});}
function roster(){const a=[];if(state.id)a.push({id:state.id,name:state.name,host:state.isHost,me:true});state.peers.forEach(p=>a.push({id:p.id,name:p.name,host:p.host,me:false}));return a;}function pushRoster(){if(state.onRoster)state.onRoster(roster(),state);}function makeRoomCode(){const L='BCDFGHJKLMNPQRSTVWXZ';let s='';for(let i=0;i<4;i++)s+=L[(Math.random()*L.length)|0];return s;}function roomFromUrl(){try{return new URLSearchParams(location.search).get('room');}catch(e){return null;}}function shareLink(){return state.room?location.origin+location.pathname+'?room='+encodeURIComponent(state.room):location.href;}async function copyLink(){try{await navigator.clipboard.writeText(shareLink());H.toast('INVITE LINK COPIED');}catch(e){H.toast(shareLink());}}
return{join,host,leave,update,onLocalShot,state,roomFromUrl,shareLink,copyLink,configured,roster,sendStart,makeRoomCode};
})();
